apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: binary
  template:
    metadata:
      labels:
        app: binary
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: binary
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args: ["echo Hello Kubernetes! && /usr/local/bin/guestbookk -http_port=80"]
