apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: image
        ports:
        - containerPort: 80