apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-probe
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: readiness-probe
  template:
    metadata:
      labels:
        app: readiness-probe
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: readiness-probe
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /bad-url
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3